sudo: false

language: python

dist: xenial

python:
  - 3.6
  - 3.7

install:
  - pip install tox-travis pipenv
  - pipenv install --dev

script:
  - tox

after_success:
  - tox -e codecov

git:
  depth: false
  quiet: true

deploy:
  provider: pypi
  on:
    tags: true
  user: manycoding
  password:
    secure: "jkMVAteM9YMxwiruke0dLU8wwrpm6qx6miQB1THlqKGgzE/snQPbL7PO8xZwKo4AvIEs7Q4eU1BBslMmRi8drAcArbElxFURS/R6UsKPJb+YNbagwbM/y68ZxRkDN+M6tjjbBL9/VA/x4FgQed/UCFoKDjfqvRFWn9P+aYqpIVtgcpvUlC7+UKBwy88vdRSZJPqTZVL0kA2WTPm4Mol88TiA2z8kBGfXzQJgQJziarwHmO1B4vL0liz29zg0DhFri93vW/ozaSoWN3vmoCRE5JDL03g13aSZ+7vXTIIJnNv2Ffnyri9s67e+YeoTlqGCnZwrZGhfQQnG9obzNTufWWuRvmabouyYBid4daUpkrwSidVHZ4HuFQ4MCjp/tTfiMdr2ygk3bg9iT/CGF4TKw6fIMT/ENRa1uNjsK/8QIOsfIBox9yRNqoW71g6UIWVLvtnXd0nkNL04n894kPeHMJ3eBbsl/UL5RuyyZESA9U7Z9fqxjYpMY2a71vNnNc4M7ApfMRlk/IYMDdGCBmrsQv5ixql2b2wWAkGwULdaTWGuolv0tdFcffzV5s/DTclzWIWT2+4fnz7M1Qjs9GRvH/nVPvdOekyDcZfk6txKotjtspRE1O30kghEJu5xVy1YVdqm+uCnLdLW6n6dnFEpnPZKBmH2WzGzEa6GsndbLk4="

